<#
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for license information.

Code generated by Microsoft (R) PSSwagger
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    Creates or Updates a Quota.

.DESCRIPTION
    Creates or Updates a Quota.

.PARAMETER Id
    ID of the resource.

.PARAMETER Type
    Type of Resource.

.PARAMETER Name
    Name of the resource.

.PARAMETER ResourceId
    The resource id.

.PARAMETER AvailabilitySetCount
    Maximum number of availability sets allowed.

.PARAMETER CoresLimit
    Maximum number of core allowed.

.PARAMETER LocationName
    Location of the resource.

.PARAMETER InputObject
    The input object of type Microsoft.AzureStack.Management.Compute.Admin.Models.Quota.

.PARAMETER Location
    Location of the resource.

.PARAMETER VirtualMachineCount
    Maximum number of virtual machines allowed.

.PARAMETER VmScaleSetCount
    Maximum number of scale sets allowed.

.PARAMETER Name
    Name of the quota.

#>
function Set-AzsComputeQuota
{
    [OutputType([Microsoft.AzureStack.Management.Compute.Admin.Models.Quota])]
    [CmdletBinding(DefaultParameterSetName='Quotas_CreateOrUpdate')]
    param(    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [string]
        $Id,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [string]
        $Type,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [string]
        $Name,
    
        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [System.String]
        $ResourceId,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [int32]
        $AvailabilitySetCount,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [int32]
        $CoresLimit,
    
        [Parameter(Mandatory = $true, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [System.String]
        $LocationName,
    
        [Parameter(Mandatory = $true, ValueFromPipeline = $true, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [Microsoft.AzureStack.Management.Compute.Admin.Models.Quota]
        $InputObject,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [string]
        $Location,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [int32]
        $VirtualMachineCount,
    
        [Parameter(Mandatory = $false, ParameterSetName = 'ResourceId_Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Parameter(Mandatory = $false, ParameterSetName = 'InputObject_Quotas_CreateOrUpdate')]
        [int32]
        $VmScaleSetCount,
    
        [Parameter(Mandatory = $true, ParameterSetName = 'Quotas_CreateOrUpdate')]
        [Alias('Quota')]
        [string]
        $Name
    )

    Begin 
    {
	    Initialize-PSSwaggerDependencies -Azure
        $tracerObject = $null
        if (('continue' -eq $DebugPreference) -or ('inquire' -eq $DebugPreference)) {
            $oldDebugPreference = $global:DebugPreference
			$global:DebugPreference = "continue"
            $tracerObject = New-PSSwaggerClientTracing
            Register-PSSwaggerClientTracing -TracerObject $tracerObject
        }
	}

    Process {
    
    $ErrorActionPreference = 'Stop'

    $NewServiceClient_params = @{
        FullClientTypeName = 'Microsoft.AzureStack.Management.Compute.Admin.ComputeAdminClient'
    }

    $GlobalParameterHashtable = @{}
    $NewServiceClient_params['GlobalParameterHashtable'] = $GlobalParameterHashtable
     
    $GlobalParameterHashtable['SubscriptionId'] = $null
    if($PSBoundParameters.ContainsKey('SubscriptionId')) {
        $GlobalParameterHashtable['SubscriptionId'] = $PSBoundParameters['SubscriptionId']
    }

    $ComputeAdminClient = New-ServiceClient @NewServiceClient_params

        
    $flattenedParameters = @('AvailabilitySetCount', 'Id', 'Type', 'CoresLimit', 'VmScaleSetCount', 'Name', 'VirtualMachineCount', 'Location')
    $utilityCmdParams = @{}
    $flattenedParameters | ForEach-Object {
        if($PSBoundParameters.ContainsKey($_)) {
            $utilityCmdParams[$_] = $PSBoundParameters[$_]
        }
    }
    $NewQuota = New-QuotaObject @utilityCmdParams

 
    $Quota = $Name

 
    if('InputObject_Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName -or 'ResourceId_Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName) {
        $GetArmResourceIdParameterValue_params = @{
            IdTemplate = '/subscriptions/{subscriptionId}/providers/Microsoft.Compute.Admin/locations/{locationName}/quotas/{quota}'
        }

        if('ResourceId_Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName) {
            $GetArmResourceIdParameterValue_params['Id'] = $ResourceId
        }
        else {
            $GetArmResourceIdParameterValue_params['Id'] = $InputObject.Id
        }
        $ArmResourceIdParameterValues = Get-ArmResourceIdParameterValue @GetArmResourceIdParameterValue_params
        $locationName = $ArmResourceIdParameterValues['locationName']

        $quota = $ArmResourceIdParameterValues['quota']
    }


    if ('Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName -or 'InputObject_Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName -or 'ResourceId_Quotas_CreateOrUpdate' -eq $PsCmdlet.ParameterSetName) {
        Write-Verbose -Message 'Performing operation CreateOrUpdateWithHttpMessagesAsync on $ComputeAdminClient.'
        $TaskResult = $ComputeAdminClient.Quotas.CreateOrUpdateWithHttpMessagesAsync($LocationName, $NewQuota)
    } else {
        Write-Verbose -Message 'Failed to map parameter set to operation method.'
        throw 'Module failed to find operation to execute.'
    }

    if ($TaskResult) {
        $GetTaskResult_params = @{
            TaskResult = $TaskResult
        }
            
        Get-TaskResult @GetTaskResult_params
        
    }
    }

    End {
        if ($tracerObject) {
            $global:DebugPreference = $oldDebugPreference
            Unregister-PSSwaggerClientTracing -TracerObject $tracerObject
        }
    }
}

