<#
Copyright (c) Microsoft and contributors.  All rights reserved.

Licensed under the Apache License, Version 2.0 (the ""License"");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

Microsoft.PowerShell.Core\Set-StrictMode -Version Latest

<#
.DESCRIPTION
   Get all filters that are applicable based on their Value.

.PARAMETER  Filters
    All filters to check for applicability. Required properties: 'Type', 'Value', 'Property'
    Supported types: 'wildcard', 'equalityOperator'
#>
function Get-ApplicableFilters {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject[]]
        $Filters
    )

    $ErrorActionPreference = 'Stop'
    foreach ($filter in $Filters) {
        $res = @{
            Filter = $filter
            Strict = $false
        }
        if ($filter.Type -eq 'wildcard') {
            if (Test-WildcardFilter -Filter $filter) {
                $res['Strict'] = $true
            }
        } 
        elseif ($filter.Type -eq 'equalityOperator') {
            if (Test-EqualityFilter -Filter $filter) {
                $res['Strict'] = $true
            }
        } elseif ($filter.Type -eq 'powershellWildcard') {
            if (Test-PSWildcardFilter -Filter $filter) {
                $res['Strict'] = $true
            }
        }
        if ($res['Strict'] -or $filter.Value) {
            $res
        }
    }
}

function Test-WildcardFilter {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject]
        $Filter
    )

    # Must contain wildcard character
    ($Filter) -and ($Filter.Value -is [System.String]) -and ($Filter.Value.Contains($Filter.Character))
}

function Test-EqualityFilter {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject]
        $Filter
    )

    # Must be specified
    ($Filter -and $Filter.Value)
}

function Test-PSWildcardFilter {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [PSCustomObject]
        $Filter
    )

    ($Filter) -and ($Filter.Value -is [System.String]) -and [WildcardPattern]::ContainsWildcardCharacters($Filter.Value)
}
