<#
Copyright (c) Microsoft and contributors.  All rights reserved.

Licensed under the Apache License, Version 2.0 (the ""License"");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.

Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

Microsoft.PowerShell.Core\Set-StrictMode -Version Latest

<#
.DESCRIPTION
   Get parameter values from the specified Azure resource identifier.

.PARAMETER  Id
    The unique resource identifier of the Azure Resource.

.PARAMETER  IdTemplate
    The unique resource identifier template of the Azure Resource.
#>
function Get-ArmResourceIdParameterValue {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]
        $Id,

        [Parameter(Mandatory = $true)]
        [string]
        $IdTemplate
    )

    Write-Verbose -Message ("Resource Id value is '{0}'" -f $Id)
    Write-Debug -Message ("Resource IdTemplate is '{0}'" -f  $IdTemplate)
    
    $IdTokens = $Id.Split('/', [System.StringSplitOptions]::RemoveEmptyEntries)
    $IdTemplateTokens = $IdTemplate.Split('/', [System.StringSplitOptions]::RemoveEmptyEntries)
    
    if ($IdTokens.Count -ne $IdTemplateTokens.Count) {
        Write-Error -Message ("Invalid resource id '{0}'. Expected id template is '{1}'." -f $Id, $IdTemplate) -ErrorId 'InvalidResourceIdValue'
        return
    }
    
    $ResourceIdParameterValues = [ordered]@{}
    for ($i = 0; $i -lt $IdTemplateTokens.Count; $i++) {
        if ($IdTokens[$i] -ne $IdTemplateTokens[$i]) {
            if ($IdTemplateTokens[$i] -notmatch '^{.*}$') {
                Write-Error -Message ("Invalid resource id '{0}'. Expected id template is '{1}'." -f $Id, $IdTemplate) -ErrorId 'InvalidResourceIdValue'
                return
            }
    
            $ResourceIdParameterValues[$IdTemplateTokens[$i].Trim('{}')] = $IdTokens[$i]
        }
    }

    return $ResourceIdParameterValues
}
