<#
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for license information.

Code generated by Microsoft (R) PSSwagger
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    Gallery item uri

.DESCRIPTION
    Gallery item uri

.PARAMETER GalleryItemUri
    Gets or sets the gallery item URI.

#>
function New-GalleryItemUriPayloadObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [string]
        $GalleryItemUri
    )
    
    $Object = New-Object -TypeName Microsoft.AzureStack.Management.Gallery.Admin.Models.GalleryItemUriPayload

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
