<#
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for license information.

Code generated by Microsoft (R) PSSwagger
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    Virtual machine extenion.

.DESCRIPTION
    Virtual machine extenion.

.PARAMETER ProvisioningState
    Provisioning state of extension.

.PARAMETER SourceBlob
    URI to azure blob.

.PARAMETER Id
    Id of the resource.

.PARAMETER Type
    Resource type.

.PARAMETER ComputeRole
    Compute role

.PARAMETER VmOsType
    Target virtaul machine operating system type necessary for deploying the extension handler

.PARAMETER Name
    Name of the resource.

.PARAMETER Location
    Location of the resource.

.PARAMETER SupportMultipleExtensions
    True if supports multiple extensions.

.PARAMETER IsSystemExtension
    Denotes if extension is for system or not.

.PARAMETER VmScaleSetEnabled
    value indicating whether the extension is enabled for virtual machine scale set support

#>
function New-VMExtensionObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [Microsoft.AzureStack.Management.Compute.Admin.Models.ProvisioningState]
        $ProvisioningState,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.AzureStack.Management.Compute.Admin.Models.AzureBlob]
        $SourceBlob,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Id,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Type,
    
        [Parameter(Mandatory = $false)]
        [string]
        $ComputeRole,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.AzureStack.Management.Compute.Admin.Models.OsType]
        $VmOsType,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Name,
    
        [Parameter(Mandatory = $false)]
        [string]
        $Location,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $SupportMultipleExtensions,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $IsSystemExtension,
    
        [Parameter(Mandatory = $false)]
        [switch]
        $VmScaleSetEnabled
    )
    
    $Object = New-Object -TypeName Microsoft.AzureStack.Management.Compute.Admin.Models.VMExtension

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
